server:
  retention: 1h
  remoteWrite:
    - queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: ${node_group_type}
  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2

alertmanager:
  enabled: false

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: ${node_group_type}

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
    NodeGroupType: ${node_group_type}

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
