apiVersion: v1
kind: Pod
metadata:
  name: fsx-taxi-driver
  namespace: emr-data-team-a
spec:
  volumes:
    - name: analytics-local-dir-ny-taxi
      persistentVolumeClaim:
        claimName: fsx-static-pvc # Static PVC pre-created by this example terraform template

  nodeSelector:
    NodeGroupType: analytics

  containers:
    - name: analytics-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: analytics-local-dir-ny-taxi
          mountPath: /static
          subPath: data # sub folder created in fsx file system and mapped to s3 bucket sync and export
          readOnly: false
  initContainers:
    - name: analytics-init-container-driver  # Don't change this name. EMR on EKS looking for this name
      image: public.ecr.aws/y4g4v0z7/busybox
      volumeMounts:
        - name: analytics-local-dir-ny-taxi
          mountPath: /static
      command: ["sh", "-c", "chmod -R 777 /static", "chown -hR +999:+1000 /static/data"]
