apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: grafana
spec:
  name: prometheus-datasource
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.prometheus.svc.cluster.local
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
